/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DetailSection: typeof import('./src/components/detail-section/detail-section.vue')['default']
    DropdownSelect: typeof import('./src/components/dropdown-select/index.vue')['default']
    GuideLogin: typeof import('./src/components/guide-login/index.vue')['default']
    HouseItemV1: typeof import('./src/components/house-item-v1/index.vue')['default']
    HouseItemV2: typeof import('./src/components/house-item-v2/index.vue')['default']
    HouseSection: typeof import('./src/components/house-section/index.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    MsgTip: typeof import('./src/components/msg-tip/index.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/index.vue')['default']
    SearchListItem: typeof import('./src/components/search-list-item/index.vue')['default']
    SearchListItemInfo: typeof import('./src/components/search-list-item-info/index.vue')['default']
    SearchListItemTitle: typeof import('./src/components/search-list-item-title/index.vue')['default']
    SideBar: typeof import('./src/components/side-bar/index.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/index.vue')['default']
    TabControl: typeof import('./src/components/tab-control/tab-control.vue')['default']
    TabSelect: typeof import('./src/components/tab-select/index.vue')['default']
    TabSelectItem: typeof import('./src/components/tab-select-item/index.vue')['default']
    ToolBar: typeof import('./src/components/tool-bar/index.vue')['default']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanIcon: typeof import('vant/es')['Icon']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    ViewHouseBtns: typeof import('./src/components/view-house-btns/index.vue')['default']
  }
}
